### ISSUE TITLE
DI problems

### ISSUE THREAD

**Issue by richbryant** [amuste/DnetIndexedDb#3]
Since I'm using MVVM, I'm attempting to inject a service, which relies my injected database, into a ViewModel.

Something's going sideways on traditional constructor injection, specifically with `IndexedDbOptions`.

Here's the error, I'll spare you the full length of it.

```
     Unhandled exception rendering component: Unable to resolve service for type 
    'DnetIndexedDb.IndexedDbOptions' while attempting to activate 
    'FunctionalDatabase.Client.Data.Local.NorthwindDb'.
    System.InvalidOperationException: Unable to resolve service for type 
    'DnetIndexedDb.IndexedDbOptions'
```

Any advice?  Here's the relevant section of Program.cs

```
    builder.Services.AddIndexedDbDatabase<NorthwindDb>(o => 
    o.UseDatabase(DataModel.GetDataModel()));

            builder.Services.AddTransient<IProductsService, ProductsService>();
            builder.Services.AddTransient<ProductsListViewModel>();
```

**Comment by richbryant** [comment]
Nevermind, I found the problem.  My mistake!

**Comment by sebfischer83** [comment]
I've got the same error, what was your mistake? :)

**Comment by tomer-ha** [comment]
For those who stumble here: the issue is that in your MyDatabase class (inheriting from IndexedDbInterop), the constructor should accept these parameters: 
(IJSRuntime jsRuntime, IndexedDbOptions<MyDatabase> indexedDbDatabaseOptions)
Notice that the IndexedDbOptions should be generic and the generic parameter is your database class.
