### ISSUE TITLE
How to add row with AutoIncrement = true

### ISSUE THREAD

**Issue by fseffert** [amuste/DnetIndexedDb#9]
I got an IndexedDbStore:

`
new IndexedDbStore
                    {
                        Name = "Staking",
                        Key = new IndexedDbStoreParameter
                        {
                            KeyPath = "id",
                            AutoIncrement = true
                        },
                        Indexes = new List<IndexedDbIndex>
                        {
                            new IndexedDbIndex
                            {
                                Name = "id",
                                Definition = new IndexedDbIndexParameter
                                {
                                    Unique = true
                                }
                            },
                            new IndexedDbIndex
                            {
                                Name = "currency",
                                Definition = new IndexedDbIndexParameter
                                {
                                    Unique = false
                                }
                            },
                            new IndexedDbIndex
                            {
                                Name = "timestamp",
                                Definition = new IndexedDbIndexParameter
                                {
                                    Unique = false
                                }
                            }
                        }
                    }
`

The first object that I add get's the id = 0. The second object can't be inserted with the following error: "DB_DATA_ADD_ERROR". I'm adding a new object like this:

`
                        Data.DtoStakingReward rw = new Data.DtoStakingReward
                        {
                            Amount = row.Amount,
                            Currency = row.Cryptocurrency,
                            Timestamp = row.Date.Date,
                            Id = new long()
                        };

                        var insertResult2 = await CakorizeDbService.AddItems<Data.DtoStakingReward>("Staking", new List<Data.DtoStakingReward> { rw });
`

 Looks like the auto-increment feature is not working? What can I do?

**Comment by amuste** [comment]
It's a library bug, I'm looking at it

**Comment by amuste** [comment]
The problem here is that the library did not support the two ways of working of keys in IndexedDB, out-of-line-keys and in-line-keys. In your specific case in-line-keys using Key generator, you can find more information here [.](https://w3c.github.io/IndexedDB/#key-generator-construct) The new version of the library supports these ways of working as follows:

 **out-of-line-keys**
 KeyPath = ""
 Use "UpdateItemsByKey" method to update items
 
 **in-line-keys using Key generators**
 KeyPath! = ""
 KeyPath property in class equal to null
 UseKeyGenerator property in IndexedDbDatabaseModel set to true
 Use "UpdateItems" method to update items
 
 **in-line-keys not using Key generators**
 KeyPath! = ""
 KeyPath property in class has value
 UseKeyGenerator property in IndexedDbDatabaseModel has no meaning
 Use "UpdateItems" method to update items

Point out that for the case of out-of-line-keys I have created a new method to update where the keys are passed.

For your case in-line-keys using Key generators. the only way I found for the moment to simulate what the specification does is by sending null in the key. When null is sent in the key the library automatically removes the keyPath property of the javascript object, when an item is saved. It is necessary to do it because otherwise the key would be represented by this value.

I will explain in more detail when I update the documentation. At the moment I have added examples to the code that illustrate all the cases.
